### ISSUE TITLE
Interpreting dereference in postconditions

### ISSUE THREAD

**Issue by yannickmoy** [xldenis/creusot#317]
This is a question to understand how dereference is interpreted in postconditions. If I take your code for [Zeroing out a list](https://github.com/xldenis/creusot/blob/master/creusot/tests/should_succeed/all_zero.rs), I can turn it into a function `bad_all_zero` which drops the list as follows:

```rust
#[ensures(len(*l) === 0)]
fn bad_all_zero(l: &mut List) {
    *l = Nil;
    proof_assert!(len(*l) === 0);
}
```

The proof assertion is proved, but not the postcondition, where `*l` is interpreted in the memory before the call to `bad_all_zero`. What's the model to keep in mind to understand this?

**Comment by sarsko** [comment]
It seems like your postcondition is not what you intended. Try
`#[ensures(len(^l) === 0)]` instead

**Comment by yannickmoy** [comment]
@sarsko yes, I understand that, I'd like to have the right model in mind to interpret `*l` in postconditions :-)

**Comment by sarsko** [comment]
Dereferencing a borrow in preconditons/postconditions is value on entry. In general `*` gives the value at that specific point(whether that is proof assertions, invariants, preconditions or postconditions)

**Comment by yannickmoy** [comment]
ok, thanks!

**Comment by jhjourdan** [comment]
Just a small note on this to explain the rationale behind this : thanks to Rust's type system, we can interpret values in Rust without thinking about "the current state of the memory". Because there is no aliasing, we give every variable a logical value which includes the data structure it is pointing to, transitively.

So, in our specs, there is no such thing as "the memory before the call", since we never reason directly about the memory state. We are referring in the post-condition to the value of the parameters at function entry, because that's the only value of the parameter visible to the caller: at function return, the callee may have dropped, moved or changed privately the value of the parameter, and that's not the caller's business. And since specs do not allow referring to "the memory state", the only value we can give in a post-condition to `*x` when `x` is a borrow is the same value it contained at function entry.

We know this is different to what do many verification tools, but we really think this is the right way to do for Creusot, since we actually do a translation to a purely functional program, so we interpret Rust programs a purely functional.

Of course, as @sarsko said, we can here refer to the value at the end of the function using `^x`.

**Comment by yannickmoy** [comment]
That makes perfect sense, but I admit it was bizarre at first, hence my question. Especially since the end of borrow for a parameter is precisely the point where the postcondition is verified, so `^p` in the logic is really `*p` in the executable code (for postconditions).

**Comment by jhjourdan** [comment]
> Especially since the end of borrow for a parameter is precisely the point where the postcondition is verified, so ^p in the logic is really *p in the executable code (for postconditions).

Well, this is true only if the borrow ends at the end of the function. If, for example, the borrow is part of the return value, then `^p` is the value at the end of the lifetime (in the callee's code). But in this case, one can refer to the state of the memory at the end of the function by referring to the content of the returned borrow.

See, e.g., the spec of index_mut for vectors.

**Comment by yannickmoy** [comment]
correct. and I see in `index_mut` the difference between
```rust
    #[ensures(*result === (@self)[@ix])]
```
for the immediate value, and:
```rust
    #[ensures(^result === (@^self)[@ix])]
```
for the value at end of borrow. (although I would expect `(@*self)[@ix])` instead of `(@self)[@ix])`, so I suppose the dereference is automatic in that case?)

**Comment by sarsko** [comment]
@yannickmoy correct.

If we look at the definition of `Model`:
(found here: https://github.com/xldenis/creusot/blob/master/creusot-contracts/src/logic/model.rs)
```rust
pub trait Model {
    type ModelTy;
    #[logic]
    fn model(self) -> Self::ModelTy;
}
```
We see that it expects an instance of `self`.
`@s` is just syntactic sugar for `s.model()`.

The auto-dereferencing is handled by Rust, see for instance: https://stackoverflow.com/questions/28519997/what-are-rusts-exact-auto-dereferencing-rules

**Comment by xldenis** [comment]
The reason is that we don't get auto-dereferencing in the desugaring of `@`. When you write `@x` you don't get `x.model()` you get `creusot_contracts::model::Model::model(x)` and then rust won't apply auto-deref. We do this to disambiguate between a user function `model` and `@`.

**Comment by sarsko** [comment]
Aha, that makes sense. Didn't think of the possible collision. Thanks @xldenis
