### ISSUE TITLE
Called impure program function in logical context error

### ISSUE THREAD

**Issue by malteafg** [xldenis/creusot#378]
I have been trying to express an elliptic curve equation in pearlite, with the purpose of automatically proving some of our Hacspec code. However, when multiplying two elements of the type that we are using, Creusot will not compile with the error: called impure program function in logical context. This happens for both multiply operations in the code below.
```
#[predicate]
pub fn mult(x: Ed25519FieldElement) -> bool {
    let lh = x * x;
    let rh = x * x;
    lh == rh
}
```
The above code works fine when using u32 instead of Ed25519FieldElement. We think that the error is because there might be something missing in the definition of Ed25519FieldElement and its associated functions, so we are curious as to what it is, that causes the "called impure program function in logical context" error? Any insight would be appreciated. We have tried marking the functions that we use with #[trusted], but it makes no difference. We also know that Creusot's Model trait is not implemented for Ed25519FieldElement, which makes it such that the == operator does not work, but we have an alternate solution for that.

**Comment by xldenis** [comment]
Since I imagine `Ed25519FieldElement` is used in both _programs_ and _specifications_ you will need to define define the _logical_ and _machine_ versions of functions like `*`, the first saying what it means _mathematically_ to multiply two elements while the second describes the machine implementation (potentially different / optimized) and you link the two via a post-condition on the physical implementation.
