### ISSUE TITLE
`[#"../src/lib.rs" 7 0 7 74]` is invalid if mlcfg file is in target/debug

### ISSUE THREAD

**Issue by suhr** [xldenis/creusot#485]
```
Error with scroll_to_loc to loc='"/home/suhr/Projects/leftpad/target/debug/src/lib.rs", line 31, characters 0-23':
anomaly: (Invalid_argument
  "(cannot open /home/suhr/Projects/leftpad/target/debug/src/lib.rs)")
```

**Comment by xldenis** [comment]
This sounds like you're using an out of date version of Why3 IDE, you will need to pin it to master as well. The side-effect is that Why3 will display and highlight the rust source code rather than the generated MLCFG, which should generally make proofs easier to work on! 

Otherwise you can disable the spans entirely by passing `--span-mode=none` to Creusot.

**Comment by suhr** [comment]
It works well if you move the mlcfg file to the root of the project. The problem is, `cargo creusot` generates mlcfg file in `target/debug` but the path specified in the mlcfg file is `../src/lib.rs`. It's a relative path, so it becomes invalid if the mlcfg file is not in the root of the project.

I'm using the git version of why3 ide. Built by https://github.com/suhr/nur-packages/blob/master/pkgs/why3/default.nix, the latest commit in the master branch of why3: https://gitlab.inria.fr/why3/why3/-/commit/e262875c0b81d96f8dcbf735946df1947a2c7fcd.

**Comment by xldenis** [comment]
Ah! In that case pass --span-mode=absolute and your problem should be fixed!

**Comment by suhr** [comment]
Awesome, thanks!
