### ISSUE TITLE
Accessing a mutable ref inside a struct causes a Why3 error

### ISSUE THREAD

**Issue by dewert99** [xldenis/creusot#486]
Examples:
```rust
use creusot_contracts::*;

struct HasMutRef<'a, T>(&'a mut T);

#[ensures(@^x.0 == 5)]
fn test(x: HasMutRef<'_, u32>) {
    *x.0 = 5
}
```
gives: `unbound function or predicate symbol '(^_)'`
```rust
use creusot_contracts::*;

struct HasMutRef<'a, T>(&'a mut T);

fn test(x: HasMutRef<'_, u32>) -> u32 {
    *x.0
}
```
gives: `unbound function or predicate symbol '(*_)'`

I think the issue is that the why3 `use prelude.Prelude` needs to be generated.

**Comment by xldenis** [comment]
Oh wow, yea, good catch! The fix is trivial but I'm not at my computer today. 

The lines [here](https://github.com/xldenis/creusot/blob/master/creusot/src/translation/specification/lower.rs#L217) need to be adjusted to import the module with `self.names.import_prelude_module(PreludeModule::Prelude)`
