### ISSUE TITLE
Add a feature for adding and using lemmas over logic functions

### ISSUE THREAD

**Issue by shiatsumat** [xldenis/creusot#72]
For some verification problems, we need to add and use lemmas over logic functions.

For example, I defined the following function.
```rust
enum List { Cons(u32, Box<List>), Nil }  use List::*;
logic! {
    fn sum(l: List) -> Int {
        match l {
            Cons(a, l2) => Int::from(a) + sum(*l2),
            Nil => 0,
        }
    }
}
```
And I needed a lemma that `forall l, sum(l) >= 0` to verify some Rust functions (especially regarding overflow checks).
However, currently Creusot doesn't have a way for achieving that.

**Comment by xldenis** [comment]
:+1: Agreed. However we should discuss this to figure out the syntax, and semantics of such a feature. 

Additionally I think that #28 would be good for this specific example: functions which are both logical and program and thus have contracts.

**Comment by xldenis** [comment]
We've found a suitable compromise for me moment: Abusing contracts and `#[trusted]` 

Instead of `lemma non_neg : forall <l : List<T>> sum(l) >=0` the idea is to write a function whose contract says the same thing and mark it as `#[trusted]`, like so:
```rust
#[trusted]
#[ensures(sum(l) >= 0)]
fn my_lemma<T>(l : List<T>)  {  () }
```

In fact this is quite similar to how lemma functions work!

**Comment by xldenis** [comment]
Now supported as logic functions with a contract.
